version: 0.2

phases:
  build:
    commands:
       - npm ci && npm run build

artifacts:
  files:
    - '**/*'

# este arquivo será usado para informar ao AWS CodeBuild quais comandos executar para construir o projeto
