name: CICD test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup nodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Image
        run: zip -r my-fav-games-demo.zip . -x '*.git*' -x '*node_modules/*' -x '*env*'
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'my-fav-games-test'
          environment_name: 'my-fav-games-test-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: my-fav-games-demo.zip

